language: node_js
node_js:
  - "0.10"
  - "0.12"
  - iojs
matrix:
  allow_failures:
    - node_js: iojs
  fast_finish: true
script: "npm run-script test-travis"
after_script: "npm install codecov.io && cat ./coverage/lcov.info | codecov"
